language: node_js

node_js:
  - 'stable'

install:
  - npm install

before_script:
  - mongo mydb_test --eval 'db.createUser({ user: "travis", pwd: "test", roles: ["readWrite"]} );'
  
services:
  - mongodb

script:
  - npm test --prefix src

cache:
  directories:
    - "node_modules"